import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ILayout } from "@/interfaces/ILayout";
import {useStyleCombing} from "@/hooks/useStyleCombing";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<ILayout>) {
  return (
    <html lang="en">
      <body className={useStyleCombing(inter.className, "body")}>{children}</body>
    </html>
  );
}
